version: '3'

services:
  blogpython_postgresql:
    image: postgres:12
    container_name: blogpython_postgresql
    volumes:
      - blogpython_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - blogpython_network

volumes:
  blogpython_postgresql:
    external: true

networks:
  blogpython_network:
    external: true


